version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker/mariadb/data:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: 123456

  php-fpm:
    build: ./docker/php-fpm
    image: xxt/php-fpm
    volumes:
      - .:/usr/share/nginx/html

  nginx:
    build: ./docker/nginx
    image: xxt/nginx
    volumes:
      - .:/usr/share/nginx/html
    links:
      - php-fpm
    # ports:
    #   - 8080:80
    # environment:
    #   NGINX_TMS_FINDER_BASE: /finder_ue/web
    #   NGINX_TMS_FINDER_ADDRESS: http://tms-finder:8080/finder_ue/web

  adminer:
    image: adminer
    restart: always
    # ports:
    #   - 9090:8080
